name: Release Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: release-production

jobs:
  deploy-services:
    environment:
      name: production
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action
        with:
          only_status: 'waiting'
          workflow_id: deploy.yaml
      - run: |
          echo "Waiting 3min"
          sleep 180
          echo "Done"
