name: Release Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          only_status: 'waiting'
          workflow_id: deploy.yaml
  deploy-services:
    needs: [ prepare ]
    environment:
      name: production
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Waiting 3min"
          sleep 180
          echo "Done"
