name: Release Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          only_status: 'waiting'
  deploy-services:
    needs: [ prepare ]
    environment:
      name: production
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Waiting 3min"
          sleep 180
          echo "Done"

  notify-cancel:
    needs: [deploy-services]
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: echo Job has been cancelled!

