name: Release Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-services:
    environment:
      name: production
    name: Deploy 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Waiting 3min"
          sleep 180
          echo "Done"
